### ISSUE TITLE
Config contains invalid JSON (comments)

### ISSUE THREAD

**Issue by mvolz** [zotero/translation-server-v2#14]
The config contains invalid JSON in the form of comments. If you do want to have comments in the config there are alternatives, such as .yaml, that might be better? 

http://yaml.org/spec/1.2/spec.html#id2759572

Yaml can be easily read in nodejs as a config file, using https://www.npmjs.com/package/js-yaml

Happy to submit a PR for this if you wish to do this.

**Comment by dstillman** [comment]
The config file is for the Node 'config' package, which [removes comments](https://github.com/lorenwest/node-config/wiki/Configuration-Files#user-content-file-formats):

> All // and /* ... */ style comments are removed before file loading, allowing you to add comments to file formats such as .json that don't natively support comments.

We could switch to YAML, but it would require an additional dependency for no particular reason (other than not getting a few warnings in an editor). Same for .json5 (which also supports comments). Given that 'config' is designed to let you do this without needing an extra parser, I don't see much need for it.

**Comment by mvolz** [comment]
Well, not an *additional* dependency, but a replacement (js-yaml instead of config) but point taken :).

**Comment by dstillman** [comment]
(Additional in that we'd still want to use 'config', which has nice features for managing configurations, and it supports YAML as a file format, but only with an extra dependency.)
