### ISSUE TITLE
PubMed page not detected

### ISSUE THREAD

**Issue by mvolz** [zotero/translation-server-v2#17]
> curl -d '{"query":"https://www.ncbi.nlm.nih.gubmed/14656957"}' --header "Content-Type: application/json" localhost:1969/search

returns 

[{"key":"ZJUJ2U6S","version":0,"itemType":"webpage","creators":[{"firstName":"National Center for Biotechnology","lastName":"Information","creatorType":"author"},{"firstName":"U. S. National Library of Medicine 8600 Rockville","lastName":"Pike","creatorType":"author"},{"firstName":"Bethesda","lastName":"MD","creatorType":"author"},{"firstName":"20894","lastName":"Usa","creatorType":"author"}],"tags":[],"url":"https://www.ncbi.nlm.nih.gov/pubmed/14656957","title":"Seventh report of the Joint National Committee on Prevention, Detection, Evaluation, and Treatment of High Blood Pressure. - PubMed - NCBI","language":"en","accessDate":"CURRENT_TIMESTAMP"}]

Looks like the pubmed translator is failing and it's falling back on embedded metadata which doesn't do a great job. 

Trace:

(3)(+0000000): Translators initialized with 523 loaded

(3)(+0000006): Listening on 0.0.0.0:1969

(3)(+0018420): HTTP GET https://www.ncbi.nlm.nih.gov/pubmed/14656957

(3)(+0001502): Translators: Looking for translators for https://www.ncbi.nlm.nih.gov/pubmed/14656957

(4)(+0000011): Translate: Binding sandbox to https://www.ncbi.nlm.nih.gov/pubmed/14656957

(4)(+0000002): Translate: Parsing code for PubMed (3d0231ce-fd4b-478c-b1d3-840389e5b68c, 2015-09-07 18:20:45)

(4)(+0000018): Translate: Parsing code for unAPI (e7e01cac-1e37-4da6-b078-a0e8343b0e98, 2018-05-12 15:58:17)

(4)(+0000001): Translate: Parsing code for COinS (05d07af9-105a-4572-99f6-a8e231c0daef, 2015-06-04 03:25:10)

(4)(+0000002): Translate: Parsing code for Embedded Metadata (951c027d-74ac-47d4-a107-9c3069ab7b48, 2018-02-13 19:20:46)

(3)(+0000003): Translate: Embedded Metadata: found 24 meta tags.

(3)(+0000001): Translate: Creating translate instance of type import in sandbox

(4)(+0000001): Translate: Binding sandbox to https://www.ncbi.nlm.nih.gov/pubmed/14656957

(4)(+0000000): Translate: Parsing code for RDF (5e3ad958-ac79-463d-812b-a86a9235c28f, 2018-05-08 19:39:38)

(3)(+0000006): Translate: Initializing RDF data store

(4)(+0000003): Translate: Parsing code for DOI (c159dcfe-8a53-4301-a499-30f6549c340d, 2016-11-05 10:57:01)

(3)(+0000008): Translate: All translator detect calls and RPC calls complete:

(3)(+0000000): 	Embedded Metadata: 320

(3)(+0000000): 	DOI: 400

(5)(+0000000): Translate: Running handler 0 for translators

(5)(+0000001): Translate: Running handler 1 for translators

(4)(+0000001): Translate: Parsing code for Embedded Metadata (951c027d-74ac-47d4-a107-9c3069ab7b48, 2018-02-13 19:20:46)

(3)(+0000002): Translate: Beginning translation with Embedded Metadata

(3)(+0000000): Translate: Embedded Metadata: found 24 meta tags.

(3)(+0000001): Translate: Creating translate instance of type import in sandbox

(4)(+0000000): Translate: Binding sandbox to https://www.ncbi.nlm.nih.gov/pubmed/14656957

(4)(+0000000): Translate: Parsing code for RDF (5e3ad958-ac79-463d-812b-a86a9235c28f, 2018-05-08 19:39:38)

(3)(+0000002): Translate: Initializing RDF data store

(3)(+0000005): Translate: Promise not available in sandbox in _itemDone()

(3)(+0000001): Translate: Saving item

(5)(+0000000): Translate: Running handler 0 for itemDone

(3)(+0000007): Translate: Title was not found in meta tags. Using document title as title

(3)(+0000001): Translate: Looking for authors in byline, vcard

(3)(+0000003): Translate: Found 0 elements with 'byline' class

(3)(+0000001): Translate: Found 1 elements with 'vcard' class

(3)(+0000001): Translate: Extracting author(s) from byline: National Center for Biotechnology Information, U.S. National Library of Medicine 8600 Rockville Pike, Bethesda MD, 20894 USA

(3)(+0000002): Translate: Promise not available in sandbox in _itemDone()

(3)(+0000000): Translate: Saving item

(3)(+0000001): Translate: Translation successful

(5)(+0000000): Translate: Running handler 0 for done

(3)(+0000000): itemToAPIJSON: Discarded field libraryCatalog: field not valid for type webpage

should be more like 

[{"itemType":"journalArticle","creators":[{"firstName":"Aram V.","lastName":"Chobanian","creatorType":"author"},{"firstName":"George L.","lastName":"Bakris","creatorType":"author"},{"firstName":"Henry R.","lastName":"Black","creatorType":"author"},{"firstName":"William C.","lastName":"Cushman","creatorType":"author"},{"firstName":"Lee A.","lastName":"Green","creatorType":"author"},{"firstName":"Joseph L.","lastName":"Izzo","creatorType":"author"},{"firstName":"Daniel W.","lastName":"Jones","creatorType":"author"},{"firstName":"Barry J.","lastName":"Materson","creatorType":"author"},{"firstName":"Suzanne","lastName":"Oparil","creatorType":"author"},{"firstName":"Jackson T.","lastName":"Wright","creatorType":"author"},{"firstName":"Edward J.","lastName":"Roccella","creatorType":"author"},{"name":"Joint National Committee on Prevention, Detection, Evaluation, and Treatment of High Blood Pressure. National Heart, Lung, and Blood Institute","creatorType":"author"},{"name":"National High Blood Pressure Education Program Coordinating Committee","creatorType":"author"}],"notes":[],"tags":[{"tag":"Adult","type":1},{"tag":"Aged","type":1},{"tag":"Antihypertensive Agents","type":1},{"tag":"Blood Pressure","type":1},{"tag":"Blood Pressure Determination","type":1},{"tag":"Cardiovascular Diseases","type":1},{"tag":"Female","type":1},{"tag":"Humans","type":1},{"tag":"Hypertension","type":1},{"tag":"Male","type":1},{"tag":"Middle Aged","type":1},{"tag":"Risk Factors","type":1}],"title":"Seventh report of the Joint National Committee on Prevention, Detection, Evaluation, and Treatment of High Blood Pressure","pages":"1206-1252","ISSN":"1524-4563","journalAbbreviation":"Hypertension","publicationTitle":"Hypertension (Dallas, Tex.: 1979)","volume":"42","issue":"6","date":"Dec 2003","language":"eng","abstractNote":"The National High Blood Pressure Education Program presents the complete Seventh Report of the Joint National Committee on Prevention, Detection, Evaluation, and Treatment of High Blood Pressure. Like its predecessors, the purpose is to provide an evidence-based approach to the prevention and management of hypertension. The key messages of this report are these: in those older than age 50, systolic blood pressure (BP) of greater than 140 mm Hg is a more important cardiovascular disease (CVD) risk factor than diastolic BP; beginning at 115/75 mm Hg, CVD risk doubles for each increment of 20/10 mm Hg; those who are normotensive at 55 years of age will have a 90% lifetime risk of developing hypertension; prehypertensive individuals (systolic BP 120-139 mm Hg or diastolic BP 80-89 mm Hg) require health-promoting lifestyle modifications to prevent the progressive rise in blood pressure and CVD; for uncomplicated hypertension, thiazide diuretic should be used in drug treatment for most, either alone or combined with drugs from other classes; this report delineates specific high-risk conditions that are compelling indications for the use of other antihypertensive drug classes (angiotensin-converting enzyme inhibitors, angiotensin-receptor blockers, beta-blockers, calcium channel blockers); two or more antihypertensive medications will be required to achieve goal BP (<140/90 mm Hg, or <130/80 mm Hg) for patients with diabetes and chronic kidney disease; for patients whose BP is more than 20 mm Hg above the systolic BP goal or more than 10 mm Hg above the diastolic BP goal, initiation of therapy using two agents, one of which usually will be a thiazide diuretic, should be considered; regardless of therapy or care, hypertension will be controlled only if patients are motivated to stay on their treatment plan. Positive experiences, trust in the clinician, and empathy improve patient motivation and satisfaction. This report serves as a guide, and the committee continues to recognize that the responsible physician's judgment remains paramount.","DOI":"10.1161/01.HYP.0000107251.49515.c2","extra":"PMID: 14656957","libraryCatalog":"PubMed"}]

**Comment by adomasven** [comment]
`detectWeb()` is failing here, which is likely due to translator expecting JS to be processed on this page. @dstillman this is a translator issue, but current translator developers have no way to properly adjust for this. We probably need a checkbox in scaffold which would make the translators run against the source html version of pages? Thoughts?

**Comment by mvolz** [comment]
But it works fine with translation-server, which is also entirely server based. So does that mean translation-server is able to process the JS but translation-server-v2 isn't?

**Comment by adomasven** [comment]
> But it works fine with translation-server, which is also entirely server based. So does that mean translation-server is able to process the JS but translation-server-v2 isn't?

Yes, translation-server creates a headless browser to load pages, but we have been pushing the translators into the direction of working without JS, so this shouldn't be necessary anymore.

**Comment by adomasven** [comment]
>>But it works fine with translation-server, which is also entirely server based. So does that mean translation-server is able to process the JS but translation-server-v2 isn't?
>
>Yes, translation-server creates a headless browser to load pages, but we have been pushing the translators into the direction of working without JS, so this shouldn't be necessary anymore.

Oh wait, this is not actually true. Seems like more xpath matching issues. I'll look into it

**Comment by adomasven** [comment]
Make sure you run "npm install" after pulling the latest commit.
